### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by sadegh1992** [viamgr/trainingapp#1]
We have some idea about project structure.
one of my colleague search about it and this is summery of her reseache's:

"Project must be created by this technologies
MVVM
Jetpack Compose
Jetpack Compose Navigation (Single activity, zero fragments)
Hilt
Retrofit
kotlin Coroutine
Room
Clean Architecture"

We have to discuses about in and choose best technologies.

**Comment by sadegh1992** [comment]
we have some other libraries for DI, like Koin and Dagger, why we must use Hilt? there is any advantage to use it?

**Comment by pariami** [comment]
> we have some other libraries for DI, like Koin and Dagger, why we must use Hilt? there is any advantage to use it?

I tried to search about Hilt and koin: and the result was that since we are going to work with kotlin, choosing koin is a more suitable option that has better performance

**Comment by viamgr** [comment]
Modular structure
Unit tests
Ui tests
CI/CD (optional)

**Comment by viamgr** [comment]
Gradle structure
